# Generated by Django 5.0 on 2024-01-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
