# Generated by Django 5.0 on 2024-01-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_profile_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
